### ISSUE TITLE
Fails on Heroku

### ISSUE THREAD

**Issue by jasdeepsingh** [kikonen/ngannotate-rails#21]
I'm trying to use this gem in my app which is being deployed on Heroku, everything works locally, however things break down in production. I've tried the solution mentioned in #10 as well, but it didn't help...

```
Running `rake db:migrate --trace` attached to terminal... up, run.3599
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `register_postprocessor' for nil:NilClass
/app/vendor/bundle/ruby/2.2.0/gems/ngannotate-rails-1.0.0/lib/ngannotate/rails/railtie.rb:34:in `block in <class:Railtie>'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `public_send'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `method_missing'
/app/config/environment.rb:5:in `<top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/app/vendor/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/app/bin/rake:4:in `<main>'
```

**Comment by kikonen** [comment]
Yes, it looks like your problem is different, since register_postprocessor - metbod is missing. Thus system is failing in initialization. If things (including this db migration) work locally it feels odd.

Q: do you have possibility to show Gemfile?



You could try locally
```
RAILS_ENV=production rake db:migrate
```
And see if it fails also then.

**Comment by kikonen** [comment]
Can you try following branch?

Gemfile
````ruby
gem 'ngannotate-rails', git: 'git://github.com/kikonen/ngannotate-rails.git', branch: 'heroku_fail_21'
````

**Comment by kikonen** [comment]
Q: Do you happen to use sprockets 3.x?

**Comment by jasdeepsingh** [comment]
@kikonen here's the Gemfile, Yes, I'm using Sprockets 3.0.3, I'll try out your branch and post my findings here...

```ruby
source 'http://rubygems.org'

ruby '2.2.0'

gem 'rails', '~> 4.2.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'state_machine'
gem 'double_entry'

gem 'devise', github: 'plataformatec/devise'#, branch: 'lm-rails-4-2'
gem 'omniauth-facebook'
gem 'rmagick', require: false
gem 'carrierwave'
gem 'pg'
gem 'haml-rails'
gem 'ngannotate-rails'
gem 'invity'
gem 'sendgrid'
gem 'gravatar-ultimate'
gem 'paypal-sdk-adaptivepayments'
gem 'paypal-sdk-invoice'
gem 'rest-client'
gem 'sidekiq'
gem 'sinatra'
gem 'slim'
gem 'fog', "~> 1.6"
gem 'newrelic_rpm'
gem 'geocoder'
gem 'googl'
gem 'jquery-placeholder-rails'
gem 'pie-rails'
gem 'chronic'
gem 'pundit'
gem 'wicked_pdf'
gem 'faker'
gem 'stamp'
gem 'wkhtmltopdf-binary'

group :production do
  gem 'puma'
  gem 'rails_12factor'
  gem 'wkhtmltopdf-heroku'
end

# Stripe
gem 'stripe', :git => 'https://github.com/stripe/stripe-ruby'

# gem 'therubyracer', platforms: :ruby

group :development, :test do 
  gem 'webrick'
  gem 'quiet_assets'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'pry'
  gem 'guard'
  gem "rb-fsevent"
  gem 'guard-rspec'
  gem 'letter_opener'
  gem 'poltergeist'
  gem 'shoulda-matchers'
  gem 'web-console', '2.0.0.beta3'
  gem 'rspec-activemodel-mocks'
end

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'
# Use unicorn as the app server
# gem 'unicorn'
# Use Capistrano for deployment
# gem 'capistrano', group: :development
# Use debugger
# gem 'debugger', group: [:development, :test]
gem 'open4'

```

**Comment by jasdeepsingh** [comment]
@kikonen the branch you suggested still fails:

```ruby
LocalJumpError: unexpected return
/app/vendor/bundle/ruby/2.2.0/bundler/gems/ngannotate-rails-6a2cbf14e234/lib/ngannotate/rails/railtie.rb:34:in `block in <class:Railtie>'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `public_send'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/railtie.rb:194:in `method_missing'
/app/config/environment.rb:5:in `<top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
/app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

I'll take a look at your commits, and chime in when I have more time this evening...

**Comment by kikonen** [comment]
https://github.com/phyllisstein/ngannotate-rails/commit/191c7d15adbcb95a810606060d2b79f82846d729#commitcomment-11103195 could be related.

**Comment by kikonen** [comment]
Sorry, have been a bit busy and not been able to look into this in detail. You might also try that change mentioned above.

**Comment by kikonen** [comment]
@jasdeepsingh Could you retry https://github.com/kikonen/ngannotate-rails/pull/22

Gemfile
````ruby
gem 'ngannotate-rails', git: 'git://github.com/kikonen/ngannotate-rails.git', branch: 'heroku_fail_21'
````
````
bundle update ngannotate-rails
````

**Comment by kikonen** [comment]
@jasdeepsingh Did you have any change trying this out?
